Upgrade to Packages directory + VPM compatibility
Upgraded from the assets folder to the "Packages" folder
Compatibility with VPM
THIS HAS ISSUES;
Packages\com.zhakami.vrc-open-world-movement\Scripts\Editor\OWML_Installer.cs(7,7): error CS0246: The type or namespace name 'SaccFlightAndVehicles' could not be found (are you missing a using directive or an assembly reference?)